language: haskell
ghc: "7.8"

before_install:
  - ./.travis.install-deps $mode --constraint="bytestring installed" --force-reinstalls

install:
  - cabal configure $mode
  - cabal build

script:
  - cabal test --show-details=always
  - ./.travis.hlint

env:
  - mode="-fWerror --enable-tests"

notifications:
  email: false
