name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10', '8.8', '8.6']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.1
    - name: Setup haskell
      uses: actions/setup-haskell@v1.1.1
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Build euphoria dependencies
      run: cabal v2-build --only-dependencies
    - name: Build euphoria
      run: cabal v2-build
    - name: Build tests dependencies
      run: cabal v2-build --enable-tests --only-dependencies
    - name: Build tests
      run: cabal v2-build --enable-tests
    - name: Run tests
      run: cabal v2-test
